src/ProdoctWebApp/Controllers/SettingsController.cs
using ProdoctCommon.Data;
using ProdoctCommon.Extensions;
using ProdoctCommon.Helpers;
using ProdoctWebApp.Helpers;
using ProdoctWebApp.Models;
using ProdoctWebApp.MVC;
using System.Linq;
using System.Web.Mvc;

namespace ProdoctWebApp.Controllers
{
    public class SettingsController : ProdoctBaseController
    {
        public SettingsController()
        {
            Helpers.General.Sleep();
        }

        [AllowUnauthorized]
        public ActionResult Index()
        {
            return View();
        }

        #region MY PROFILE

        #region READ

        [AllowUnauthorized]
        public ActionResult MyProfile()
        {
            return PartialView("_Profile");
        }

        [AllowUnauthorized]
        public ActionResult MyInfo()
        {
            var user = LoggedInUser;
            var model = new MyInfoModel(user);

            return PartialView("_ProfileInfo", model);
        }

        [AllowUnauthorized]
        public ActionResult ChangePassword()
        {
            var model = new ChangePasswordModel();
            return PartialView("_ProfilePassword", model);
        }

        #endregion

        #region UPDATE

        [HttpPost]
        [AllowUnauthorized]
        public JsonResult MyInfo(MyInfoModel model)
        {
            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var user = LoggedInUser;
            var emailResult = user.SetEmail(model.Email, APP.Common);
            if (emailResult.Error)
                return JsonResultInvalidData(emailResult.Message);

            user.Name = model.Name;
            user.Mobile = model.Mobile;

            var result = DB.Users.Update(user).ToStandardResult("Updated");
            
            if (!result.Error)
            {
                foreach(var staff in emailResult.StaffsAffected)
                    DB.Staffs.Update(staff);
            }

            var redirectUrl = string.Empty;
            if (emailResult.Changed)
            {
                LinkHelper.ScheduleUserEmailVerify(user, Url);
                redirectUrl = Url.RouteUrl(RouteName.Settings);
            }

            return Json(new
            {
                HasError = result.Error,
                Message = result.Message,
                RedirecUrl = redirectUrl
            });
        }

        [HttpPost]
        [AllowUnauthorized]
        public JsonResult ChangePassword(ChangePasswordModel model)
        {
            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var user = LoggedInUser;
            if (!AuthenticationHelper.VerifyHashedPassword(user.PasswordHash, model.CurrentPassword))
                return JsonResultInvalidData("Incorrect Current Password");

            user.SetPassword(model.NewPassword);
            var result = DB.Users.Update(user).ToStandardResult("Password changed");
            return JsonStandardResult(result);
        }

        #endregion

        #endregion

        #region PRACTICE PROFILE

        #region READ

        public ActionResult PracticeProfile()
        {
            if (!IsAdmin)
                return PartialViewAccessDenied();

            var model = new PracticeSettingsModel(Practice);
            return PartialView("_Practice", model);
        }

        #endregion

        #region UPDATE

        [HttpPost]
        public JsonResult PracticeProfile(PracticeSettingsModel model)
        {
            if (!IsAdmin)
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var practice = Practice;
            model.ToPractice(practice);

            var result = DB.Practices.Update(practice).ToStandardResult("Updated");
            return JsonStandardResult(result);
        }

        #endregion

        #endregion

        #region PRACTICE STAFF

        #region READ

        public ActionResult Staff()
        {
            if (!IsAdmin)
                return PartialViewAccessDenied();

            var model = DB.Staffs.Get(new string[] { "Name", "Role", "Privileges.IsAdmin", "Title", "HasAccepted", "AllowLogin", "LastLogin" })
                          .AsQueryable()
                          .OrderBy(x => x.Role)
                          .Select(x => new StaffListModel(x))
                          .ToList();

            return PartialView("_Staff", model);
        }

        #endregion

        #region CREATE

        public ActionResult StaffAdd()
        {
            if (!IsAdmin)
                return PartialViewModalAccessDenied();

            return PartialView("_StaffAdd", new StaffAddModel());
        }

        [HttpPost]
        public JsonResult StaffAdd(StaffAddModel model)
        {
            if (!IsAdmin)
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var message = string.Empty;
            if (!CheckStaffAddConditions(model, out message))
                return JsonResultInvalidData(message);

            var userResult = model.GetUser();
            if (userResult.Error)
                return JsonResultInvalidData(string.Format("User not created. {0}", userResult.Message));
            else
                ProcessUserResult(userResult);

            var staff = model.ToStaff();
            var result = DB.Staffs.Add(staff).ToStandardResult("Staff added");
            var staffId = string.Empty;

            if (!result.Error)
            {
                if (staff.AllowLogin)
                {
                    staffId = staff.Id;
                    result.Message = string.Empty;
                    LinkHelper.ScheduleStaffInvitation(staff, Url);
                }
            }

            return Json(new
            {
                HasError = result.Error,
                Message = result.Message,
                Id = staffId
            });
        }

        private void ProcessUserResult(StaffGetUserResult userResult)
        {
            if (userResult.IsNew)
                DB.Users.Add(userResult.User);
            else
                DB.Users.Update(userResult.User);
        }

        private bool CheckStaffAddConditions(StaffAddModel model, out string message)
        {
            message = string.Empty;
            var duplicate = DB.Staffs.GetByEmail(model.Email);
            if(duplicate != null)
            {
                message = "Another staff member uses same Email Id";
                return false;
            }

            return true;
        }

        public ActionResult DoctorAdd()
        {
            if (!IsAdmin)
                return PartialViewModalAccessDenied();

            return PartialView("_DoctorAdd", new DoctorAddModel());
        }

        [HttpPost]
        public JsonResult DoctorAdd(DoctorAddModel model)
        {
            if (!IsAdmin)
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var message = string.Empty;
            if (!CheckDoctorAddConditions(model, out message))
                return JsonResultInvalidData(message);

            var userResult = model.GetUser();
            if (userResult.Error)
                return JsonResultInvalidData(string.Format("User not created. {0}", userResult.Message));
            else
                ProcessUserResult(userResult);

            var doctor = model.ToDoctor();
            var result = DB.Staffs.Add(doctor).ToStandardResult("Doctor added");
            var doctorId = string.Empty;

            if (!result.Error)
            {
                if (doctor.AllowLogin)
                {
                    doctorId = doctor.Id;
                    result.Message = string.Empty;
                    LinkHelper.ScheduleStaffInvitation(doctor, Url);
                }
            }

            return Json(new
            {
                HasError = result.Error,
                Message = result.Message,
                Id = doctorId
            });
        }

        private bool CheckDoctorAddConditions(DoctorAddModel model, out string message)
        {
            message = string.Empty;
            var duplicate = DB.Staffs.GetByEmail(model.Email);
            if (duplicate != null)
            {
                message = "Another staff member uses same Email Id";
                return false;
            }

            return true;
        }

        #endregion

        #region UPDATE

        public ActionResult StaffEdit(string id)
        {
            if (!IsAdmin)
                return PartialViewModalAccessDenied();

            var staff = DB.Staffs.GetById(id);
            if (staff == null)
                return PartialViewModalNotFound();

            var model = new StaffEditModel(staff);
            return PartialView("_StaffEdit", model);
        }

        public ActionResult StaffBasics(string id)
        {
            if (!IsAdmin)
                return PartialViewAccessDenied();

            var staff = DB.Staffs.GetById(id);
            if (staff == null)
                return PartialViewNotFound();

            var model = new StaffBasicsModel(staff, APP.Common.UserId);
            return PartialView("_StaffEditBasics", model);
        }

        public ActionResult StaffPrivileges(string id)
        {
            if (!IsAdmin)
                return PartialViewAccessDenied();

            var staff = DB.Staffs.GetById(id);
            if (staff == null)
                return PartialViewNotFound();


src/ProdoctWebApp/Views/Settings/_Calendar.cshtml
@model ProdoctWebApp.Models.CalendarSettingsModel

<ul class="nav nav-tabs single-tab-heading">
    <li role="presentation"><a class="heading">Calendar Settings</a></li>
</ul>

@using (Ajax.BeginForm("Calendar", "Settings", null, new AjaxOptions
                        {
                            OnBegin = "pr.settings.calendar.before",
                            OnSuccess = "pr.settings.calendar.after",
                            OnFailure = "pr.settings.calendar.error"
                        }, new { @class = "form-horizontal" }))
{
    <div class="form-horizontal-fixed padding">
        
        <div class="form-group">
            <label for="ShowCanceledAppointments" class="col-sm-2 control-label">Canceled Appointments</label>
            <div class="col-sm-10">
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(x => x.ShowCanceledAppointments)
                        Show Canceled Appointments
                    </label>
                </div>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10 btn-container">
                <button id="btnUpdateCalendarSettings" type="submit"
                        class="btn btn-success btn-block submitter"
                        data-remove-on-submit="btn-success"
                        data-add-on-submit="btn-default">
                    Update
                </button>
            </div>
        </div>

    </div>
}

src/ProdoctWebApp/Views/Settings/_DoctorAdd.cshtml
@model ProdoctWebApp.Models.DoctorAddModel

<div class="pr-modal-content">
    <div class="pr-modal-header">
        <div class="pr-modal-header-content">
            <div class="modal-close"><span class="glyphicon glyphicon-remove"></span></div>
            <div class="pr-modal-title"><h3>Add Doctor</h3></div>
        </div>
    </div>

    <div class="pr-modal-body">
        @using (Ajax.BeginForm("DoctorAdd", "Settings", null, new AjaxOptions
                        {
                            OnBegin = "pr.settings.doctor.add.before",
                            OnSuccess = "pr.settings.doctor.add.after",
                            OnFailure = "pr.settings.doctor.add.error"
                        }, new { @class = "form-horizontal", id = "addDoctorForm" }))
        {
            <div class="form-horizontal-fixed col-sm-8">
                
                <div class="form-group">
                    <label for="add_DoctorName" class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Name, new { id = "add_DoctorName", placeholder = "Name", @class = "form-control focus-on-load" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_DoctorTitle" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Title, new { id = "add_DoctorTitle", placeholder = "Title", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_DoctorEmail" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Email, new { id = "add_DoctorEmail", placeholder = "Email", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_DoctorMobile" class="col-sm-2 control-label">Mobile</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Mobile, new { id = "add_DoctorMobile", placeholder = "Mobile", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_CalendarColor" class="col-sm-2 control-label">Calendar Color</label>
                    <div class="col-sm-10">
                        <div class="input-group calendar-color">
                            @Html.TextBoxFor(x => x.CalendarColor, new { id = "add_CalendarColor", placeholder = "Calendar Color", @class = "form-control" })
                            <span class="input-group-addon"><i></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_DoctorAllowLogin" class="col-sm-2 control-label">Login</label>
                    <div class="col-sm-10">
                        <div class="checkbox">
                            <label>
                                @Html.CheckBoxFor(x => x.AllowLogin, new { id = "add_DoctorAllowLogin" })
                                Allow user to log in
                            </label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-10 btn-container">
                        <button id="btnAddDoctor" type="submit"
                                class="btn btn-success btn-block submitter"
                                data-remove-on-submit="btn-success"
                                data-add-on-submit="btn-default">
                            Add Doctor
                        </button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>

src/ProdoctWebApp/Views/Settings/_DoctorEditBasics.cshtml
@model ProdoctWebApp.Models.DoctorBasicsModel

@using (Ajax.BeginForm("DoctorBasics", "Settings", null, new AjaxOptions
                {
                    OnBegin = "pr.settings.doctor.editBasics.before",
                    OnSuccess = "pr.settings.doctor.editBasics.after",
                    OnFailure = "pr.settings.doctor.editBasics.error"
                }, new { @class = "form-horizontal", id = "editDoctorForm" }))
{
    <div class="form-horizontal-fixed col-sm-8 padding">
                
        @Html.HiddenFor(x => x.Id)

        <div class="form-group">
            <label for="edit_DoctorName" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { id = "edit_DoctorName", placeholder = "Name", @class = "form-control focus-on-load" })
            </div>
        </div>

        <div class="form-group">
            <label for="edit_DoctorTitle" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Title, new { id = "edit_DoctorTitle", placeholder = "Title", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="edit_DoctorEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                @if(Model.IsSelf)
                {
                    @Html.TextBoxFor(x => x.Email, new { id = "edit_DoctorEmail", placeholder = "Email", @class = "form-control", @readonly = true })
                }
                else
                { 
                    @Html.TextBoxFor(x => x.Email, new { id = "edit_DoctorEmail", placeholder = "Email", @class = "form-control" })
                }
            </div>
        </div>

        <div class="form-group">
            <label for="edit_DoctorMobile" class="col-sm-2 control-label">Mobile</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Mobile, new { id = "edit_DoctorMobile", placeholder = "Mobile", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="edit_CalendarColor" class="col-sm-2 control-label">Calendar Color</label>
            <div class="col-sm-10">
                <div class="input-group calendar-color">
                    @Html.TextBoxFor(x => x.CalendarColor, new { id = "edit_CalendarColor", placeholder = "Calendar Color", @class = "form-control" })
                    <span class="input-group-addon"><i></i></span>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="edit_DoctorAllowLogin" class="col-sm-2 control-label">Login</label>
            <div class="col-sm-10">
                <div class="checkbox">
                    <label>
                        @if(Model.IsSelf)
                        {
                        @Html.CheckBoxFor(x => x.AllowLogin, new { id = "edit_DoctorAllowLogin", disabled = "disabled" })
                        }
                        else
                        { 
                        @Html.CheckBoxFor(x => x.AllowLogin, new { id = "edit_DoctorAllowLogin" })
                        }
                        Allow user to log in
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10 btn-container">
                <button id="btnDoctorBasics" type="submit"
                        class="btn btn-success btn-block submitter"
                        data-remove-on-submit="btn-success"
                        data-add-on-submit="btn-default">
                    Update
                </button>
            </div>
        </div>

        @if(!Model.IsSelf)
        { 
        <div class="form-group">
            <div id="doctorMoreOptionsContainer" class="col-sm-12 more-options-container">
                <div class="more-options">
                    <label>Options:</label>
                    <button id="deleteDoctor" class="delete-staff btn-link submitter">Delete Permanently</button>
                </div>
            </div>
        </div>
        }
        
    </div>
}

src/ProdoctWebApp/Views/Settings/_DoctorEditPrivileges.cshtml
@model ProdoctWebApp.Models.DoctorPrivilegesModel

@using (Ajax.BeginForm("DoctorPrivileges", "Settings", null, new AjaxOptions
                {
                    OnBegin = "pr.settings.doctor.editPrivileges.before",
                    OnSuccess = "pr.settings.doctor.editPrivileges.after",
                    OnFailure = "pr.settings.doctor.editPrivileges.error"
                }, new { @class = "form-horizontal" }))
{
    <div class="form-horizontal-fixed col-sm-8 padding">

        @Html.HiddenFor(x => x.Id)

        <div class="form-group alert alert-info">
            <label class="col-sm-2 control-label">Administrator?</label>
            <div class="col-sm-5">
                <div class="checkbox">
                    <label>@Html.CheckBoxFor(x => x.IsAdmin, new { id = "doctor_IsAdmin" }) Yes</label>
                </div>
            </div>
        </div>

        <div class="form-group privileges @(Model.IsAdmin ? "admin" : string.Empty)">

            <div class="form-group">
                <label class="col-sm-2 control-label">Appointments</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.AppointmentsRead) Read</label>
                    </div>
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.AppointmentsWrite) Write</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Patients</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.PatientsRead) Read</label>
                    </div>
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.PatientsWrite) Write</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Medicines</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.InventoryRead) Read</label>
                    </div>
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.InventoryWrite) Write</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label">Finance</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.FinanceRead) Read</label>
                    </div>
                    <div class="checkbox">
                        <label>@Html.CheckBoxFor(x => x.FinanceWrite) Write</label>
                    </div>
                </div>
            </div>

        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10 btn-container">
                <button id="btnDoctorPrivileges" type="submit"
                        class="btn btn-success btn-block submitter"
                        data-remove-on-submit="btn-success"
                        data-add-on-submit="btn-default">
                    Update
                </button>
            </div>
        </div>

    </div>
}

src/ProdoctWebApp/Views/Settings/_Practice.cshtml
@model ProdoctWebApp.Models.PracticeSettingsModel

<ul class="nav nav-tabs single-tab-heading">
    <li role="presentation"><a class="heading">Practice Profile</a></li>
</ul>

@using (Ajax.BeginForm("PracticeProfile", "Settings", null, new AjaxOptions
                        {
                            OnBegin = "pr.settings.practice.before",
                            OnSuccess = "pr.settings.practice.after",
                            OnFailure = "pr.settings.practice.error"
                        }, new { @class = "form-horizontal" }))
{
    <div class="form-horizontal-fixed padding">
        <div class="form-group">
            <label for="PracticeName" class="col-sm-2 control-label">Practice Name</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { id = "PracticeName", placeholder = "Practice Name", @class = "form-control focus-on-load" })
            </div>
        </div>

        <div class="form-group">
            <label for="PracticeEmail" class="col-sm-2 control-label">Practice Email</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Email, new { id = "PracticeEmail", placeholder = "Practice Email", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="PracticeContactNumber" class="col-sm-2 control-label">Contact Number</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.ContactNumber, new { id = "PracticeContactNumber", placeholder = "Practice Contact Number", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="PracticeWebsite" class="col-sm-2 control-label">Practice Website</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Website, new { id = "PracticeWebsite", placeholder = "Practice Website", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="PracticeTimezone" class="col-sm-2 control-label">Timezone</label>
            <div class="col-sm-10">
                @Html.DropDownListFor(x => x.Timezone, Model.AllTimezones, new { id = "PracticeTimezone", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10 btn-container">
                <button id="btnUpdatePracticeProfile" type="submit"
                        class="btn btn-success btn-block submitter"
                        data-remove-on-submit="btn-success"
                        data-add-on-submit="btn-default">
                    Update
                </button>
            </div>
        </div>
    </div>
}

src/ProdoctWebApp/Views/Settings/_ProfileInfo.cshtml
@model ProdoctWebApp.Models.MyInfoModel

@using (Ajax.BeginForm("MyInfo", "Settings", null, new AjaxOptions
                        {
                            OnBegin = "pr.settings.myInfo.before",
                            OnSuccess = "pr.settings.myInfo.after",
                            OnFailure = "pr.settings.myInfo.error"
                        }, new { @class = "form-horizontal" }))
{
    <div class="form-horizontal-fixed">
        
        <div class="form-group">
            <label for="MyName" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { id = "MyName", placeholder = "My Name", @class = "form-control focus-on-load" })
            </div>
        </div>

        <div class="form-group">
            <label for="MyEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Email, new { id = "MyEmail", placeholder = "My Email", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="MyMobile" class="col-sm-2 control-label">Mobile</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Mobile, new { id = "MyMobile", placeholder = "My Mobile", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10 btn-container">
                <button id="btnUpdateMyInfo" type="submit"
                        class="btn btn-success btn-block submitter"
                        data-remove-on-submit="btn-success"
                        data-add-on-submit="btn-default">
                    Update
                </button>
            </div>
        </div>
    </div>
}

src/ProdoctWebApp/Views/Settings/_ProfilePassword.cshtml
@model ProdoctWebApp.Models.ChangePasswordModel

@using (Ajax.BeginForm("ChangePassword", "Settings", null, new AjaxOptions
                        {
                            OnBegin = "pr.settings.password.before",
                            OnSuccess = "pr.settings.password.after",
                            OnFailure = "pr.settings.password.error"
                        }, new { @class = "form-horizontal" }))
{
    <div class="form-horizontal-fixed">

        <div class="form-group">
            <label for="CurrentPassword" class="col-sm-2 control-label">Current Password</label>
            <div class="col-sm-10">
                @Html.PasswordFor(x => x.CurrentPassword, new { placeholder = "Current Password", @class = "form-control focus-on-load" })
            </div>
        </div>

        <div class="form-group">
            <label for="NewPassword" class="col-sm-2 control-label">New Password</label>
            <div class="col-sm-10">
                @Html.PasswordFor(x => x.NewPassword, new { placeholder = "New Password", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label for="ConfirmPassword" class="col-sm-2 control-label">Confirm Password</label>
            <div class="col-sm-10">
                @Html.PasswordFor(x => x.ConfirmPassword, new { placeholder = "Confirm New Password", @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10 btn-container">
                <button id="btnChangePassword" type="submit"
                        class="btn btn-success btn-block submitter"
                        data-remove-on-submit="btn-success"
                        data-add-on-submit="btn-default">
                    Change
                </button>
            </div>
        </div>
    </div>
}

src/ProdoctWebApp/Views/Settings/_StaffRow.cshtml
@model ProdoctWebApp.Models.StaffListModel

<tr class="staff-row modal-link" data-modal="editStaffContainer"
    data-get="/Settings/StaffEdit/@Model.Id" data-target="#editStaffContainer"
    data-loading-message="Loading @Model.Name ..."
    data-broadcast-on-load="StaffEditLoaded">
    <td class="name">@Model.Name</td>
    <td>@Model.Title</td>
    <td>@Model.Privileges</td>
    <td>@Html.Partial("_StaffRowCellLastLogin", Model)</td>
</tr>

src/ProdoctWebApp/Views/Settings/_StaffRowCellLastLogin.cshtml
@model ProdoctWebApp.Models.StaffListModel

@if (!Model.AllowLogin)
{
    <div class="alert alert-danger" title="User login isn't allowed">
        Login Disabled
    </div>
}
else if (!Model.HasAccepted)
{
    <div class="alert alert-warning" title="User hasn't accepted the invitation yet">
        Not Verified
    </div>
}
else
{
    @Model.LastLogin
}