src/ProdoctWebApp/Controllers/Finance/ExpensesController.cs
using ProdoctCommon.Data;
using ProdoctCommon.Dto;
using ProdoctCommon.Extensions;
using ProdoctCommon.Helpers;
using ProdoctWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProdoctWebApp.Controllers
{
    public class ExpensesController : ProdoctBaseController
    {
        public ExpensesController()
        {
            Helpers.General.Sleep();
        }

        #region READ

        public ActionResult Reports()
        {
            if (!CanView())
                return PartialViewModalAccessDenied();

            var model = new ReportsModel(Practice.Timezone);
            model.AllReports = new List<ReportsSelectItemModel>
            {
                new ReportsSelectItemModel { Text = "All Expenses", Get = "/Expenses/All", Selected = true },
                new ReportsSelectItemModel { Text = "Expenses by Category", Get = "/Expenses/ByCategory" }
            };

            return PartialView(FinanceModel.GetViewName("Expenses/_Reports"), model);
        }




        public ActionResult All(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportAllExpensesModel(GetAllExpensesChart(start, end),
                                                   GetAllExpensesList(start, end),
                                                   start,
                                                   end);

            return PartialView(FinanceModel.GetViewName("Expenses/_ReportAllExpenses"), model);
        }

        private List<ChartDateAmount> GetAllExpensesChart(DateTime start, DateTime end)
        {
            return DB.Expenses.GetAllExpensesChart(start, end);
        }

        private ExpensesListModel GetAllExpensesList(DateTime start, DateTime end)
        {
            var settings = new ListSettingsReport { Start = start, End = end };
            return GetAllExpensesList(settings);
        }

        private ExpensesListModel GetAllExpensesList(ListSettingsReport settings)
        {
            var count = 0;
            var expenses = DB.Expenses.GetList(settings, out count).Select(x => new ExpenseModel(x)).ToList();

            return new ExpensesListModel
            {
                Expenses = expenses,
                MoreExist = !(expenses.Count < settings.Take),
                Skip = settings.Skip + expenses.Count
            };
        }




        public ActionResult List(ListSettingsReport settings)
        {
            var model = GetAllExpensesList(settings);
            var html = RenderPartialViewToString(FinanceModel.GetViewName("Expenses/_List"), model);
            return Json(new
            {
                HasError = false,
                Message = string.Empty,
                Html = html
            });
        }




        public ActionResult ByCategory(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportByCategoryModel(DB.Expenses.GetByCategoryChart(start, end));
            return PartialView(FinanceModel.GetViewName("Expenses/_ReportByCategory"), model);
        }




        private bool CheckPreconditionsForReport(ReportsModel model, out DateTime start, out DateTime end, out string message)
        {
            start = DateTimeHelper.FromDateRangePicker(model.Start).ToUtc();
            end = DateTimeHelper.FromDateRangePicker(model.End).ToUtc();
            message = string.Empty;

            if (start > end)
            {
                message = "Invalid date range";
                return false;
            }

            if (end.Subtract(start).TotalDays > 31)
            {
                message = "Maximum date range - 31 days";
                return false;
            }

            return true;
        }


        #endregion

        #region CREATE

        public ActionResult Add()
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            return PartialView(FinanceModel.GetViewName("Expenses/_Add"), new ExpenseAddModel());
        }

        [HttpPost]
        public ActionResult Add(ExpenseAddModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var expense = model.ToExpense();
            var result = DB.Expenses.Add(expense).ToStandardResult("Expense added");
            return JsonStandardResult(result);
        }

        #endregion

        #region UPDATE

        public ActionResult Edit(string id)
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            var expense = DB.Expenses.GetById(id);
            if (expense == null)
                return PartialViewModalNotFound();

            var model = new ExpenseEditModel(expense);
            return PartialView(FinanceModel.GetViewName("Expenses/_Edit"), model);
        }

        [HttpPost]
        public ActionResult Edit(ExpenseEditModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var message = string.Empty;
            if (!CheckExpenseEditConditions(model, out message))
                return JsonResultInvalidData(message);

            var expense = DB.Expenses.GetById(model.Id);
            if (expense == null)
                return JsonResultInvalidData("Record not found!");

            model.ToExpense(expense);
            var result = DB.Expenses.Update(expense).ToStandardResult("Updated");
            return JsonStandardResult(result);
        }

        private bool CheckExpenseEditConditions(ExpenseEditModel model, out string message)
        {
            message = string.Empty;
            return true;
        }

        #endregion

        #region DELETE

        public JsonResult Delete(string id)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            var expense = DB.Expenses.GetById(id);
            if (expense == null)
                return JsonResultInvalidData("Record not found!");

            var message = string.Empty;
            if (!CheckPreconditionsForDeletingExpense(expense, out message))
                return JsonResultInvalidData(message);

            var result = DB.Expenses.Remove(expense).ToStandardResult("Deleted");
            return JsonStandardResult(result);
        }

        private bool CheckPreconditionsForDeletingExpense(Expense expense, out string message)
        {
            message = string.Empty;
            return true;
        }

        #endregion

        private bool CanView()
        {
            return Privileges.FinanceRead;
        }

        private bool CanWrite()
        {
            return Privileges.FinanceWrite;
        }
    }
}

src/ProdoctWebApp/Controllers/Finance/FinanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProdoctWebApp.Controllers
{
    public class FinanceController : ProdoctBaseController
    {
        public FinanceController()
        {
            Helpers.General.Sleep();
        }

        #region READ

        public ActionResult Index()
        {
            if (!CanView())
                return RedirectToAllowedRoute();

            return View();
        }

        #endregion




        private bool CanView()
        {
            return Privileges.FinanceRead;
        }

        private bool CanWrite()
        {
            return Privileges.FinanceWrite;
        }
    }
}

src/ProdoctWebApp/Controllers/Finance/ProfitabilityController.cs
using ProdoctWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProdoctWebApp.Controllers
{
    public class ProfitabilityController : ProdoctBaseController
    {
        public ProfitabilityController()
        {
            Helpers.General.Sleep();
        }

        #region READ

        public ActionResult Reports()
        {
            if (!CanView())
                return PartialViewModalAccessDenied();

            return PartialView(FinanceModel.GetViewName("Profitability/_Reports"));
        }

        #endregion




        private bool CanView()
        {
            return Privileges.FinanceRead;
        }

        private bool CanWrite()
        {
            return Privileges.FinanceWrite;
        }
    }
}

src/ProdoctWebApp/Views/Finance/Expenses/_Add.cshtml
@model ProdoctWebApp.Models.ExpenseAddModel

<div class="pr-modal-content">
    <div class="pr-modal-header">
        <div class="pr-modal-header-content">
            <div class="modal-close"><span class="glyphicon glyphicon-remove"></span></div>
            <div class="pr-modal-title"><h3>Add Expense</h3></div>
        </div>
    </div>

    <div class="pr-modal-body">
        @using (Ajax.BeginForm("Add", "Expenses", null, new AjaxOptions
                        {
                            OnBegin = "pr.finance.expenses.add.before",
                            OnSuccess = "pr.finance.expenses.add.after",
                            OnFailure = "pr.finance.expenses.add.error"
                        }, new { @class = "form-horizontal", id = "addExpenseForm" }))
        {
            <div class="form-horizontal-fixed col-sm-8">

                <div class="form-group">
                    <label for="add_ExpenseCategory" class="col-sm-2 control-label">Category</label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => x.Category, Model.AllCategories, new { id = "add_ExpenseCategory", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_ExpenseDate" class="col-sm-2 control-label">Date</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Date, new { id = "add_ExpenseDate", placeholder = "Date", @class = "form-control datepicker", @readonly = true })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_ExpenseAmount" class="col-sm-2 control-label">Amount</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Amount, new { htmlAttributes = new { @class = "form-control focus-on-load", id = "add_ExpenseAmount", placeholder = "Amount" } })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_ExpenseMode" class="col-sm-2 control-label">Mode</label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => x.Mode, Model.AllModes, new { id = "add_ExpenseMode", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_ExpenseNotes" class="col-sm-2 control-label">Notes</label>
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.Notes, new { id = "add_ExpenseNotes", placeholder = "Notes", @class = "form-control", rows = 3 })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-10 btn-container">
                        <button id="btnAddExpense" type="submit"
                                class="btn btn-success btn-block submitter"
                                data-remove-on-submit="btn-success"
                                data-add-on-submit="btn-default">
                            Add Expense
                        </button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>

src/ProdoctWebApp/Views/Finance/Expenses/_Edit.cshtml
@model ProdoctWebApp.Models.ExpenseEditModel

<div class="pr-modal-content">
    <div class="pr-modal-header">
        <div class="pr-modal-header-content">
            <div class="modal-close"><span class="glyphicon glyphicon-remove"></span></div>
            <div class="pr-modal-title"><h3>Edit Expense</h3></div>
        </div>
    </div>

    <div class="pr-modal-body">
        @using (Ajax.BeginForm("Edit", "Expenses", null, new AjaxOptions
                        {
                            OnBegin = "pr.finance.expenses.edit.before",
                            OnSuccess = "pr.finance.expenses.edit.after",
                            OnFailure = "pr.finance.expenses.edit.error"
                        }, new { @class = "form-horizontal", id = "editExpenseForm" }))
        {
            <div class="form-horizontal-fixed col-sm-8">
                
                @Html.HiddenFor(x => x.Id, new { id = "edit_ExpenseId" })

                <div class="form-group">
                    <label for="edit_ExpenseCategory" class="col-sm-2 control-label">Category</label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => x.Category, Model.AllCategories, new { id = "edit_ExpenseCategory", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="edit_ExpenseDate" class="col-sm-2 control-label">Date</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Date, new { id = "edit_ExpenseDate", placeholder = "Date", @class = "form-control datepicker", @readonly = true })
                    </div>
                </div>

                <div class="form-group">
                    <label for="edit_ExpenseAmount" class="col-sm-2 control-label">Amount</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Amount, new { htmlAttributes = new { @class = "form-control focus-on-load", id = "edit_ExpenseAmount", placeholder = "Amount" } })
                    </div>
                </div>

                <div class="form-group">
                    <label for="edit_ExpenseMode" class="col-sm-2 control-label">Mode</label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => x.Mode, Model.AllModes, new { id = "edit_ExpenseMode", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="edit_ExpenseNotes" class="col-sm-2 control-label">Notes</label>
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.Notes, new { id = "edit_ExpenseNotes", placeholder = "Notes", @class = "form-control", rows = 3 })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-10 btn-container">
                        <button id="btnEditExpense" type="submit"
                                class="btn btn-success btn-block submitter"
                                data-remove-on-submit="btn-success"
                                data-add-on-submit="btn-default">
                            Update Record
                        </button>
                    </div>
                </div>

                <div class="form-group">
                    <div id="expenseMoreOptionsContainer" class="col-sm-12 more-options-container">
                        <div class="more-options">
                            <label>Options:</label>
                            <button id="deleteExpense" class="delete-expense btn-link submitter">Delete Permanently</button>
                        </div>
                    </div>
                </div>

            </div>
        }
    </div>
</div>

src/ProdoctWebApp/Views/Finance/Expenses/_List.cshtml
@model ProdoctWebApp.Models.ExpensesListModel

@if (Model.Expenses.Count == 0)
{
    <tr>
        <td class="no-more-results-container" colspan="4">
            <span class="no-more-results">End of list</span>
        </td>
    </tr>
}
else
{

    foreach (var expense in Model.Expenses)
    {
        <tr class="income modal-link" data-id="@expense.Id"
            data-modal="editExpenseContainer" data-target="#editExpenseContainer"
            data-get="/Expenses/Edit/@expense.Id"
            data-loading-message="Loading Expense Record ..."
            data-broadcast-on-load="expenseEditFormLoaded">

            <td class="expense-date">@expense.Date</td>
            <td class="expense-mode">@expense.Mode</td>
            <td class="expense-amount">@expense.Amount</td>
            <td class="expense-category">@expense.Category</td>

        </tr>
    }

    if (Model.MoreExist)
    {
        <tr class="get-more-container next-set">
            <td colspan="4">
                <button id="expensesGetMore" class="btn btn-default get-more" data-skip="@Model.Skip">Get more</button>
            </td>
        </tr>
    }
}

src/ProdoctWebApp/Views/Finance/Expenses/_ReportAllExpenses.cshtml
@using ProdoctWebApp.Models;
@model ReportAllExpensesModel

<div class="report-chart-container">
    <div class="report-chart">
        <canvas id="myChart"></canvas>
    </div>
</div>

<div class="report-list-container">
    <table class="table table-hover table-expenses">
        <thead>
            <tr>
                <th>Date</th>
                <th>Mode</th>
                <th>Amount</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            @Html.Partial(FinanceModel.GetViewName("Expenses/_List"), Model.List)
        </tbody>
    </table>
</div>

<script>
    $(document).trigger(pr.finance.events.reportLoadedAllExpenses, ['@Html.Raw(Model.ChartJson)']);
</script>

src/ProdoctWebApp/Views/Finance/Expenses/_ReportByCategory.cshtml
@using ProdoctWebApp.Models;
@model ReportByCategoryModel

<div class="report-chart-container">
    <div class="report-chart">
        <canvas id="myChart"></canvas>
    </div>
</div>

<div class="report-list-container">
    <table class="table table-hover table-incomes">
        <thead>
            <tr>
                <th></th>
                <th>Category</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            
            @foreach (var category in Model.List.Categories)
            {
                <tr>
                    <td><div class="income-color" style="background: @category.Color"></div></td>
                    <td class="income-category">@category.Category</td>
                    <td class="income-amount">@category.Amount</td>
                </tr>
            }

        </tbody>
    </table>
</div>

<script>
    $(document).trigger(pr.finance.events.reportLoadedExpensesByCategory, ['@Html.Raw(Model.ChartJson)']);
</script>

src/ProdoctWebApp/Views/Finance/Expenses/_Reports.cshtml
@model ProdoctWebApp.Models.ReportsModel

<div class="report-header clearfix">

    <div class="report-selector">
        <select id="reportSelector" class="form-control ajax-getter">
            @foreach (var report in Model.AllReports)
            {
                <option value="@report.Text"
                        data-get="@report.Get"
                        data-data-function="finance.getReportParams"
                        data-target="#reportContainer"
                        data-loading-message="Loading @report.Text report ..."
                        data-broadcast-on-load="reportLoaded"
                        @(report.Selected ? "selected" : string.Empty)>
                    @report.Text
                </option>
            }
        </select>

    </div>

    <div class="report-duration">
        <span class="glyphicon glyphicon-chevron-left stepper previous"></span>
        <div class="input-daterange input-group" id="datepicker">
            @Html.TextBoxFor(x => x.Start, new { name = "start", @class = "input-sm form-control start", @readonly = true })
            <span class="input-group-addon">to</span>
            @Html.TextBoxFor(x => x.End, new { name = "end", @class = "input-sm form-control end", @readonly = true })
        </div>
        <span class="glyphicon glyphicon-chevron-right stepper next"></span>
    </div>

</div>

<div id="reportContainer" class="report-container"></div>