src/ProdoctWebApp/Controllers/Finance/ExpensesController.cs
using ProdoctCommon.Data;
using ProdoctCommon.Dto;
using ProdoctCommon.Extensions;
using ProdoctCommon.Helpers;
using ProdoctWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProdoctWebApp.Controllers
{
    public class ExpensesController : ProdoctBaseController
    {
        public ExpensesController()
        {
            Helpers.General.Sleep();
        }

        #region READ

        public ActionResult Reports()
        {
            if (!CanView())
                return PartialViewModalAccessDenied();

            var model = new ReportsModel(Practice.Timezone);
            model.AllReports = new List<ReportsSelectItemModel>
            {
                new ReportsSelectItemModel { Text = "All Expenses", Get = "/Expenses/All", Selected = true },
                new ReportsSelectItemModel { Text = "Expenses by Category", Get = "/Expenses/ByCategory" }
            };

            return PartialView(FinanceModel.GetViewName("Expenses/_Reports"), model);
        }




        public ActionResult All(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportAllExpensesModel(GetAllExpensesChart(start, end),
                                                   GetAllExpensesList(start, end),
                                                   start,
                                                   end);

            return PartialView(FinanceModel.GetViewName("Expenses/_ReportAllExpenses"), model);
        }

        private List<ChartDateAmount> GetAllExpensesChart(DateTime start, DateTime end)
        {
            return DB.Expenses.GetAllExpensesChart(start, end);
        }

        private ExpensesListModel GetAllExpensesList(DateTime start, DateTime end)
        {
            var settings = new ListSettingsReport { Start = start, End = end };
            return GetAllExpensesList(settings);
        }

        private ExpensesListModel GetAllExpensesList(ListSettingsReport settings)
        {
            var count = 0;
            var expenses = DB.Expenses.GetList(settings, out count).Select(x => new ExpenseModel(x)).ToList();

            return new ExpensesListModel
            {
                Expenses = expenses,
                MoreExist = !(expenses.Count < settings.Take),
                Skip = settings.Skip + expenses.Count
            };
        }




        public ActionResult List(ListSettingsReport settings)
        {
            var model = GetAllExpensesList(settings);
            var html = RenderPartialViewToString(FinanceModel.GetViewName("Expenses/_List"), model);
            return Json(new
            {
                HasError = false,
                Message = string.Empty,
                Html = html
            });
        }




        public ActionResult ByCategory(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportByCategoryModel(DB.Expenses.GetByCategoryChart(start, end));
            return PartialView(FinanceModel.GetViewName("Expenses/_ReportByCategory"), model);
        }




        private bool CheckPreconditionsForReport(ReportsModel model, out DateTime start, out DateTime end, out string message)
        {
            start = DateTimeHelper.FromDateRangePicker(model.Start).ToUtc();
            end = DateTimeHelper.FromDateRangePicker(model.End).ToUtc();
            message = string.Empty;

            if (start > end)
            {
                message = "Invalid date range";
                return false;
            }

            if (end.Subtract(start).TotalDays > 31)
            {
                message = "Maximum date range - 31 days";
                return false;
            }

            return true;
        }


        #endregion

        #region CREATE

        public ActionResult Add()
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            return PartialView(FinanceModel.GetViewName("Expenses/_Add"), new ExpenseAddModel());
        }

        [HttpPost]
        public ActionResult Add(ExpenseAddModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var expense = model.ToExpense();
            var result = DB.Expenses.Add(expense).ToStandardResult("Expense added");
            return JsonStandardResult(result);
        }

        #endregion

        #region UPDATE

        public ActionResult Edit(string id)
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            var expense = DB.Expenses.GetById(id);
            if (expense == null)
                return PartialViewModalNotFound();

            var model = new ExpenseEditModel(expense);
            return PartialView(FinanceModel.GetViewName("Expenses/_Edit"), model);
        }

        [HttpPost]
        public ActionResult Edit(ExpenseEditModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var message = string.Empty;
            if (!CheckExpenseEditConditions(model, out message))
                return JsonResultInvalidData(message);

            var expense = DB.Expenses.GetById(model.Id);
            if (expense == null)
                return JsonResultInvalidData("Record not found!");

            model.ToExpense(expense);
            var result = DB.Expenses.Update(expense).ToStandardResult("Updated");
            return JsonStandardResult(result);
        }

        private bool CheckExpenseEditConditions(ExpenseEditModel model, out string message)
        {
            message = string.Empty;
            return true;
        }

        #endregion

        #region DELETE

        public JsonResult Delete(string id)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            var expense = DB.Expenses.GetById(id);
            if (expense == null)
                return JsonResultInvalidData("Record not found!");

            var message = string.Empty;
            if (!CheckPreconditionsForDeletingExpense(expense, out message))
                return JsonResultInvalidData(message);

            var result = DB.Expenses.Remove(expense).ToStandardResult("Deleted");
            return JsonStandardResult(result);
        }

        private bool CheckPreconditionsForDeletingExpense(Expense expense, out string message)
        {
            message = string.Empty;
            return true;
        }

        #endregion

        private bool CanView()
        {
            return Privileges.FinanceRead;
        }

        private bool CanWrite()
        {
            return Privileges.FinanceWrite;
        }
    }
}

src/ProdoctWebApp/Controllers/Finance/IncomeController.cs
using ProdoctCommon.Data;
using ProdoctCommon.Dto;
using ProdoctCommon.Extensions;
using ProdoctCommon.Helpers;
using ProdoctWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ProdoctWebApp.Controllers
{
    public class IncomeController : ProdoctBaseController
    {
        public IncomeController()
        {
            Helpers.General.Sleep();
        }

        #region READ

        public ActionResult Reports()
        {
            if (!CanView())
                return PartialViewModalAccessDenied();

            var model = new ReportsModel(Practice.Timezone);
            model.AllReports = new List<ReportsSelectItemModel>
            {
                new ReportsSelectItemModel { Text = "All Income", Get = "/Income/All", Selected = true },
                new ReportsSelectItemModel { Text = "Income per Doctor", Get = "/Income/PerDoctor" },
                new ReportsSelectItemModel { Text = "Income by Category", Get = "/Income/ByCategory" }
            };

            return PartialView(FinanceModel.GetViewName("Income/_Reports"), model);
        }




        public ActionResult All(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportAllIncomeModel(GetAllIncomeChart(start, end), 
                                                 GetAllIncomeList(start, end), 
                                                 start, 
                                                 end);
            
            return PartialView(FinanceModel.GetViewName("Income/_ReportAllIncome"), model);
        }

        private List<ChartDateAmount> GetAllIncomeChart(DateTime start, DateTime end)
        {
            return DB.Incomes.GetAllIncomeChart(start, end);
        }

        private IncomeListModel GetAllIncomeList(DateTime start, DateTime end)
        {
            var settings = new ListSettingsReport { Start = start, End = end };
            return GetAllIncomeList(settings);
        }

        private IncomeListModel GetAllIncomeList(ListSettingsReport settings)
        {
            var count = 0;
            var incomes = DB.Incomes.GetList(settings, out count);
            var doctors = new List<Doctor>();
            var patients = new List<Patient>();
            if (incomes.Fees != null && incomes.Fees.Count > 0)
            {
                var doctorIds = incomes.Fees.Select(x => x.DoctorId).ToList();
                doctors = DB.Staffs.Get<Doctor>().Where(x => doctorIds.Contains(x.Id)).ToList();

                var patientIds = incomes.Fees.Select(x => x.PatientId).ToList();
                patients = DB.Patients.Get(new string[] { "Name" }).Where(x => patientIds.Contains(x.Id)).ToList();
            }
            var list = incomes.Incomes.Select(x => new IncomeModel(x, incomes.Fees, doctors, patients)).ToList();

            return new IncomeListModel
            {
                Incomes = list,
                MoreExist = !(list.Count < settings.Take),
                Skip = settings.Skip + list.Count
            };
        }




        public ActionResult List(ListSettingsReport settings)
        {
            var model = GetAllIncomeList(settings);
            var html = RenderPartialViewToString(FinanceModel.GetViewName("Income/_List"), model);
            return Json(new
            {
                HasError = false,
                Message = string.Empty,
                Html = html
            });
        }




        public ActionResult PerDoctor(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportPerDoctorModel(DB.Incomes.GetPerDoctorChart(start, end));
            return PartialView(FinanceModel.GetViewName("Income/_ReportPerDoctor"), model);
        }




        public ActionResult ByCategory(ReportsModel settings)
        {
            DateTime start, end;
            var message = string.Empty;
            if (!CheckPreconditionsForReport(settings, out start, out end, out message))
                return PartialViewError(message);

            var model = new ReportByCategoryModel(DB.Incomes.GetByCategoryChart(start, end));
            return PartialView(FinanceModel.GetViewName("Income/_ReportByCategory"), model);
        }




        private bool CheckPreconditionsForReport(ReportsModel model, out DateTime start, out DateTime end, out string message)
        {
            start = DateTimeHelper.FromDateRangePicker(model.Start).ToUtc();
            end = DateTimeHelper.FromDateRangePicker(model.End).ToUtc();
            message = string.Empty;

            if (start > end)
            {
                message = "Invalid date range";
                return false;
            }

            if(end.Subtract(start).TotalDays > 31)
            {
                message = "Maximum date range - 31 days";
                return false;
            }

            return true;
        }

        #endregion

        #region CREATE

        public ActionResult Add()
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            return PartialView(FinanceModel.GetViewName("Income/_Add"), new IncomeAddModel());
        }

        [HttpPost]
        public ActionResult Add(IncomeAddModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            if(string.IsNullOrWhiteSpace(model.Category))
                return JsonResultInvalidData();

            if (model.Category.ToLower() == "fees")
                return AddFees(model);

            return AddIncome(model);
        }

        private ActionResult AddIncome(IncomeAddModel model)
        {
            ModelState.Remove("PatientNameOrMobile");
            ModelState.Remove("PatientId");
            ModelState.Remove("DoctorId");

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var income = model.ToIncome();
            var result = DB.Incomes.Add(income).ToStandardResult("Income added");
            return JsonStandardResult(result);
        }

        private ActionResult AddFees(IncomeAddModel model)
        {
            ModelState.Remove("PatientNameOrMobile");

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var fees = model.ToFees();
            var result = DB.Incomes.Add(fees).ToStandardResult("Fees added");
            return JsonStandardResult(result);
        }

        #endregion

        #region UPDATE

        public ActionResult Edit(string id)
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            var income = DB.Incomes.GetById(id);
            if (income == null)
                return PartialViewModalNotFound();

            var model = new IncomeEditModel(income);
            return PartialView(FinanceModel.GetViewName("Income/_Edit"), model);
        }

        [HttpPost]
        public ActionResult Edit(IncomeEditModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var message = string.Empty;
            if (!CheckIncomeEditConditions(model, out message))
                return JsonResultInvalidData(message);

            var income = DB.Incomes.GetById(model.Id);
            if (income == null)
                return JsonResultInvalidData("Record not found!");

            model.ToIncome(income);
            var result = DB.Incomes.Update(income).ToStandardResult("Updated");
            return JsonStandardResult(result);
        }

        private bool CheckIncomeEditConditions(IncomeEditModel model, out string message)
        {
            message = string.Empty;
            return true;
        }




        public ActionResult EditFees(string id)
        {
            if (!CanWrite())
                return PartialViewModalAccessDenied();

            var fees = DB.Incomes.GetById<Fees>(id);
            if (fees == null)
                return PartialViewModalNotFound();

            var model = new FeesEditModel(fees);
            return PartialView(FinanceModel.GetViewName("Income/_EditFees"), model);
        }

        [HttpPost]
        public ActionResult EditFees(FeesEditModel model)
        {
            if (!CanWrite())
                return JsonResultAccessDenied();

            ModelState.Remove("Category");
            if (!ModelState.IsValid)
                return JsonResultInvalidData();

            var message = string.Empty;
            if (!CheckIncomeEditConditions(model, out message))
                return JsonResultInvalidData(message);

            var fees = DB.Incomes.GetById<Fees>(model.Id);
            if (fees == null)
                return JsonResultInvalidData("Record not found!");

            model.ToFees(fees);
            var result = DB.Incomes.Update(fees).ToStandardResult("Updated");
            return JsonStandardResult(result);
        }

        #endregion

        #region DELETE

        public JsonResult Delete(string id)
        {
            if (!CanWrite())

src/ProdoctWebApp/Views/Finance/Income/AddFees.cshtml
@model ProdoctWebApp.Models.FeesAddModel
@{
    ViewBag.Title = "Add Fees";
}

<div class="content">
    <div id="addFeesContainer" class="pr-modal modal-full show">
        <div class="pr-modal-content">
            <div class="pr-modal-header">
                <div class="pr-modal-header-content">
                    <div class="pr-modal-title"><h3>Add Fees</h3></div>
                </div>
            </div>

            <div class="pr-modal-body">
                @using (Ajax.BeginForm("AddFees", "Income", null, new AjaxOptions
                        {
                            OnBegin = "pr.finance.addFees.before",
                            OnSuccess = "pr.finance.addFees.after",
                            OnFailure = "pr.finance.addFees.error"
                        }, new { @class = "form-horizontal add-fees", id = "addFeesForm" }))
                {
                    <div class="form-horizontal-fixed col-sm-8">

                        <div class="form-group">
                            <label for="add_FeesCategory" class="col-sm-2 control-label">Category</label>
                            <div class="col-sm-10">
                                @Html.DropDownListFor(x => x.Category, Model.AllCategories, new { id = "add_FeesCategory", @class = "form-control" })
                            </div>
                        </div>

                        @Html.HiddenFor(x => x.AppointmentId)

                        <div class="patient-fees patient-summary form-group">
                            @Html.HiddenFor(x => x.PatientId, new { @class = "patient-id" })
                            <div class="form-group">
                                <label class="col-sm-2 control-label">Patient</label>
                                <div class="col-sm-10">
                                    <div class="form-control patient-summary-content">
                                        <div class="patient-name">@Model.PatientName</div>
                                        <div class="patient-locality">@Model.PatientLocality</div>
                                        <div class="patient-mobile">@Model.PatientMobile</div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="add_FeesDoctorId" class="col-sm-2 control-label">Doctor</label>
                                <div class="col-sm-10">
                                    @Html.DropDownListFor(x => x.DoctorId, Model.AllDoctors, new { id = "add_FeesDoctorId", @class = "form-control doctor-id", disabled = true })
                                    @Html.HiddenFor(x => x.DoctorId)
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="add_FeesDate" class="col-sm-2 control-label">Date</label>
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Date, new { id = "add_FeesDate", placeholder = "Date", @class = "form-control", @readonly = true })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="add_FeesAmount" class="col-sm-2 control-label">Amount</label>
                            <div class="col-sm-10">
                                @Html.EditorFor(x => x.Amount, new { htmlAttributes = new { @class = "form-control focus-on-load", id = "add_FeesAmount", placeholder = "Amount" } })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="add_FeesMode" class="col-sm-2 control-label">Mode</label>
                            <div class="col-sm-10">
                                @Html.DropDownListFor(x => x.Mode, Model.AllModes, new { id = "add_FeesMode", @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="add_FeesNotes" class="col-sm-2 control-label">Notes</label>
                            <div class="col-sm-10">
                                @Html.TextAreaFor(x => x.Notes, new { id = "add_FeesNotes", placeholder = "Notes", @class = "form-control", rows = 3 })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label"></label>
                            <div class="col-sm-10 btn-container">
                                <button id="btnAddFees" type="submit"
                                        class="btn btn-success btn-block submitter"
                                        data-remove-on-submit="btn-success"
                                        data-add-on-submit="btn-default">
                                    Add Fees
                                </button>
                            </div>
                        </div>

                    </div>
                }

                <div id="feesAdded" class="fees-added">
                    <div>Added successfully</div>
                    <div><a href="#" onclick="window.close()">Close this window</a></div>
                </div>
            </div>



        </div>
    </div>
</div>

@section css
{
    @Styles.Render("~/bundles/css/finance")
}

@section scripts
{
    @Scripts.Render("~/bundles/js/finance")
}

src/ProdoctWebApp/Views/Finance/Income/_Add.cshtml
@model ProdoctWebApp.Models.IncomeAddModel

<div class="pr-modal-content">
    <div class="pr-modal-header">
        <div class="pr-modal-header-content">
            <div class="modal-close"><span class="glyphicon glyphicon-remove"></span></div>
            <div class="pr-modal-title"><h3>Add Income</h3></div>
        </div>
    </div>

    <div class="pr-modal-body">
        @using (Ajax.BeginForm("Add", "Income", null, new AjaxOptions
                        {
                            OnBegin = "pr.finance.income.add.before",
                            OnSuccess = "pr.finance.income.add.after",
                            OnFailure = "pr.finance.income.add.error"
                        }, new { @class = "form-horizontal", id = "addIncomeForm" }))
        {
            <div class="form-horizontal-fixed col-sm-8">
                
                <div class="form-group">
                    <label for="add_IncomeCategory" class="col-sm-2 control-label">Category</label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => x.Category, Model.AllCategories, new { id = "add_IncomeCategory", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group patient-fees">
                    <div class="patient-input form-group">
                        <label for="add_IncomePatient" class="col-sm-2 control-label">Patient</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.PatientNameOrMobile, new { id = "add_IncomePatientNameOrMobile", placeholder = "Patient's Name / Mobile", @class = "form-control patient-name-input" })
                        </div>
                    </div>

                    <div class="patient-summary form-group">
                        @Html.HiddenFor(x => x.PatientId, new { @class = "patient-id" })
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Patient</label>
                            <div class="col-sm-10">
                                <div class="form-control patient-summary-content">
                                    <div class="patient-name"></div>
                                    <div class="patient-locality"></div>
                                    <div class="patient-mobile"></div>
                                    <span class="glyphicon glyphicon-remove patient-change" title="Change"></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="add_IncomeDoctorId" class="col-sm-2 control-label">Doctor</label>
                        <div class="col-sm-10">
                           @Html.DropDownListFor(x => x.DoctorId, Model.AllDoctors, new { id = "add_IncomeDoctorId", @class = "form-control doctor-id" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_IncomeDate" class="col-sm-2 control-label">Date</label>
                    <div class="col-sm-10">
                        @Html.TextBoxFor(x => x.Date, new { id = "add_IncomeDate", placeholder = "Date", @class = "form-control datepicker", @readonly = true })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_IncomeAmount" class="col-sm-2 control-label">Amount</label>
                    <div class="col-sm-10">
                        @Html.EditorFor(x => x.Amount, new { htmlAttributes = new { @class = "form-control focus-on-load", id = "add_IncomeAmount", placeholder = "Amount" } })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_IncomeMode" class="col-sm-2 control-label">Mode</label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(x => x.Mode, Model.AllModes, new { id = "add_IncomeMode", @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="add_IncomeNotes" class="col-sm-2 control-label">Notes</label>
                    <div class="col-sm-10">
                        @Html.TextAreaFor(x => x.Notes, new { id = "add_IncomeNotes", placeholder = "Notes", @class = "form-control", rows = 3 })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-10 btn-container">
                        <button id="btnAddIncome" type="submit"
                                class="btn btn-success btn-block submitter"
                                data-remove-on-submit="btn-success"
                                data-add-on-submit="btn-default">
                            Add Income
                        </button>
                    </div>
                </div>

            </div>
        }
    </div>
</div>

src/ProdoctWebApp/Views/Finance/Income/_List.cshtml
@model ProdoctWebApp.Models.IncomeListModel

@if (Model.Incomes.Count == 0)
{
    <tr>
        <td class="no-more-results-container" colspan="4">
            <span class="no-more-results">End of list</span>
        </td>
    </tr>
}
else
{

    foreach (var income in Model.Incomes)
    {
        var url = "Edit";
        var broadcast = "incomeEditFormLoaded";
        var message = "Income";
        
        if (income.Category == "Fees")
        {
            url = "EditFees";
            broadcast = "feesEditFormLoaded";
            message = "Fees";
        }
        
        <tr class="income modal-link" data-id="@income.Id"
            data-modal="editIncomeContainer" data-target="#editIncomeContainer"
            data-get="/Income/@url/@income.Id"
            data-loading-message="Loading @message Record ..."
            data-broadcast-on-load="@broadcast">

            <td class="income-date">@income.Date</td>
            <td class="income-mode">@income.Mode</td>
            <td class="income-amount">@income.Amount</td>
            <td class="income-category">
                @income.Category

                @if (!string.IsNullOrWhiteSpace(income.DoctorName))
                {
                    <span class="income-doctor-name">(@income.DoctorName)</span>
                }
            </td>

        </tr>
    }

    if (Model.MoreExist)
    {
        <tr class="get-more-container next-set">
            <td colspan="4">
                <button id="incomesGetMore" class="btn btn-default get-more" data-skip="@Model.Skip">Get more</button>
            </td>
        </tr>
    }
}

src/ProdoctWebApp/Views/Finance/Income/_ReportAllIncome.cshtml
@using ProdoctWebApp.Models;
@model ReportAllIncomeModel

<div class="report-chart-container">
    <div class="report-chart">
        <canvas id="myChart"></canvas>
    </div>
</div>

<div class="report-list-container">
    <table class="table table-hover table-incomes">
        <thead>
            <tr>
                <th>Date</th>
                <th>Mode</th>
                <th>Amount</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            @Html.Partial(FinanceModel.GetViewName("Income/_List"), Model.List)
        </tbody>
    </table>
</div>

<script>
    $(document).trigger(pr.finance.events.reportLoadedAllIncome, ['@Html.Raw(Model.ChartJson)']);
</script>